/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CursorJNI */

#ifndef _Included_CursorJNI
#define _Included_CursorJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CursorJNI
 * Method:    isVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CursorJNI_isVisible
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
